### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by jesbrz** [MIERUNE/qgis-plugx-plugin#160]
I get this error when I try to install:

```
Plugin 'qgis-plugx-plugin' could not be loaded due to an error calling its classFactory() method

ImportError: cannot import name 'write_json' from 'utils' (/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py) 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-plugx-plugin/__init__.py", line 9, in classFactory
    from qgis2plugx import QGIS2PlugX
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-plugx-plugin/qgis2plugx.py", line 7, in 
    from ui.main_dialog import MainDialog
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-plugx-plugin/ui/main_dialog.py", line 22, in 
    from translator.vector.label import generate_label_vector
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis-plugx-plugin/translator/vector/label.py", line 7, in 
    from utils import write_json
ImportError: cannot import name 'write_json' from 'utils' (/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py)

```

Versión de Python: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Versión de QGIS: 3.32.3-Lima Lima, 67d46100b5b

**Comment by bordoray** [comment]
Hi @jesbrz ,  thanks for your feedback.
`ImportError: cannot import name 'write_json' from 'utils' (/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/utils.py) `

It looks that plugin install makes a conflict with another plugin (here `qgis2web`).
If you disable qgis2web and relaunch QGIS, it should work.

I agree that it is not a solution though, I will try to fix it.

**Comment by bordoray** [comment]
Close with #161
